name: Build Docker
on: push
jobs:
 Docker-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t test-image ./server --file ./server/dockerfile
      - run: >- '
             docker run -d 
             --name app-server8000
             -p 8000:8000 
             --restart unless-stopped 
             test-image'
      - run: docker ps -a
      - run: 'curl 127.0.0.1:8000'
