name: Build Docker
on: push
jobs:
 Docker-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t test-image . --file server/dockerfile
      - run: 'curl 127.0.0.1:8000'
